spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hobby_it?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.naver.com
    port: 465
    username: ejk9767@naver.com
    password: dbqksA505
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  profiles:
    include:
      - file


springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    enabled: true

logging:
  level:
    org:
      springframework:
        web: debug

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
